# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(570, 428)
        self.Button_send = QtWidgets.QPushButton(Dialog)
        self.Button_send.setGeometry(QtCore.QRect(440, 380, 75, 23))
        self.Button_send.setCheckable(True)
        self.Button_send.setObjectName("Button_send")
        self.Button_start = QtWidgets.QPushButton(Dialog)
        self.Button_start.setGeometry(QtCore.QRect(440, 30, 101, 41))
        self.Button_start.setCheckable(True)
        self.Button_start.setObjectName("Button_start")
        self.Text_chat = QtWidgets.QTextEdit(Dialog)
        self.Text_chat.setGeometry(QtCore.QRect(23, 20, 381, 331))
        self.Text_chat.setObjectName("Text_chat")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(40, 360, 361, 51))
        self.textEdit_2.setObjectName("textEdit_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Button_send.setText(_translate("Dialog", "发送"))
        self.Button_start.setText(_translate("Dialog", "启动服务器"))
